# Generated by Django 6.0.1 on 2026-02-09 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='coachaccesskey',
            name='used_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'GUILD_MASTER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_new_assignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coachaccesskey',
            name='key',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='goal',
            field=models.CharField(default='General Fitness', max_length=50),
        ),
        migrations.CreateModel(
            name='AssessmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waist_circumference', models.FloatField(help_text='Inches')),
                ('medical_history', models.TextField(blank=True, help_text='Past or present conditions')),
                ('injuries', models.TextField(blank=True, help_text='Fractures, chronic pain')),
                ('food_preference', models.CharField(choices=[('Vegan', 'Vegan'), ('Jain', 'Jain'), ('Lacto-Veg', 'Lacto-Vegetarian'), ('Ovo-Veg', 'Ovo-Vegetarian'), ('Pescatarian', 'Pescatarian'), ('Non-Veg', 'Non-Vegetarian')], max_length=50)),
                ('meals_per_day', models.IntegerField(default=3)),
                ('typical_breakfast', models.TextField(blank=True)),
                ('typical_lunch', models.TextField(blank=True)),
                ('typical_dinner', models.TextField(blank=True)),
                ('typical_snacks', models.TextField(blank=True)),
                ('tea_coffee_cups', models.CharField(blank=True, max_length=50)),
                ('alcohol_frequency', models.CharField(blank=True, max_length=50)),
                ('food_allergies', models.TextField(blank=True)),
                ('exercise_experience', models.TextField(blank=True, help_text='Years of experience, if any')),
                ('preferred_exercise', models.CharField(blank=True, help_text='Gym, Yoga, Running, etc.', max_length=100)),
                ('days_available', models.CharField(help_text='Days per week available', max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
