# Generated by Django 6.0.1 on 2026-02-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers_coachaccesskey_used_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentform',
            name='bicep_size',
            field=models.FloatField(blank=True, help_text='Inches', null=True),
        ),
        migrations.AddField(
            model_name='assessmentform',
            name='chest_size',
            field=models.FloatField(blank=True, help_text='Inches', null=True),
        ),
        migrations.AddField(
            model_name='assessmentform',
            name='thigh_size',
            field=models.FloatField(blank=True, help_text='Inches', null=True),
        ),
        migrations.AlterField(
            model_name='assessmentform',
            name='days_available',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assessmentform',
            name='exercise_experience',
            field=models.TextField(blank=True, help_text='Years of experience'),
        ),
        migrations.AlterField(
            model_name='assessmentform',
            name='preferred_exercise',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
