# Generated by Django 6.0.1 on 2026-02-21 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_assessmentform_bicep_size_assessmentform_chest_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachaccesskey',
            name='key_type',
            field=models.CharField(choices=[('COACH', 'Coach'), ('SUPER_COACH', 'Super Coach')], default='COACH', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='super_coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'SUPER_COACH'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_coaches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('RECRUIT', 'Recruit'), ('GUILD_MASTER', 'Guild Master'), ('SUPER_COACH', 'Super Coach'), ('HIGH_COUNCIL', 'High Council')], default='RECRUIT', max_length=20),
        ),
    ]
