# Generated by Django 6.0.1 on 2026-03-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_age_customuser_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='coins',
            new_name='coin_balance',
        ),
        migrations.AddField(
            model_name='customuser',
            name='player_class',
            field=models.CharField(blank=True, choices=[('Vanguard', 'Vanguard'), ('Assassin', 'Assassin'), ('Ranger', 'Ranger'), ('Mage', 'Mage')], max_length=50, null=True),
        ),
    ]
