from django.core.management.base import BaseCommand
from workouts.models import Exercise


class Command(BaseCommand):
    help = "Seed workout exercises for the plan builder (Title Case groups, 20 per group)"

    def handle(self, *args, **kwargs):
        exercises = [
            # CHEST (20)
            {"name": "Barbell Bench Press", "muscle_group": "Chest", "difficulty": "Intermediate", "equipment_needed": "Barbell, Bench", "description": "Classic compound chest press."},
            {"name": "Incline Dumbbell Press", "muscle_group": "Chest", "difficulty": "Intermediate", "equipment_needed": "Dumbbells, Incline Bench", "description": "Upper chest focus."},
            {"name": "Decline Bench Press", "muscle_group": "Chest", "difficulty": "Intermediate", "equipment_needed": "Barbell, Decline Bench", "description": "Lower chest emphasis."},
            {"name": "Dumbbell Flyes", "muscle_group": "Chest", "difficulty": "Beginner", "equipment_needed": "Dumbbells, Bench", "description": "Chest stretch and squeeze."},
            {"name": "Cable Crossover", "muscle_group": "Chest", "difficulty": "Intermediate", "equipment_needed": "Cable Machine", "description": "Constant tension chest isolation."},
            {"name": "Push-Ups", "muscle_group": "Chest", "difficulty": "Beginner", "equipment_needed": "None", "description": "Bodyweight chest builder."},
            {"name": "Incline Push-Ups", "muscle_group": "Chest", "difficulty": "Beginner", "equipment_needed": "None", "description": "Upper chest bodyweight press."},
            {"name": "Diamond Push-Ups", "muscle_group": "Chest", "difficulty": "Intermediate", "equipment_needed": "None", "description": "Inner chest and triceps."},
            {"name": "Dumbbell Bench Press", "muscle_group": "Chest", "difficulty": "Beginner", "equipment_needed": "Dumbbells, Bench", "description": "Unilateral chest development."},
            {"name": "Chest Dips", "muscle_group": "Chest", "difficulty": "Intermediate", "equipment_needed": "Dip Bars", "description": "Lower chest compound movement."},
            {"name": "Pec Deck Machine", "muscle_group": "Chest", "difficulty": "Beginner", "equipment_needed": "Pec Deck Machine", "description": "Isolation chest fly machine."},
            {"name": "Landmine Chest Press", "muscle_group": "Chest", "difficulty": "Intermediate", "equipment_needed": "Barbell, Landmine", "description": "Shoulder-friendly chest press."},
            {"name": "Close-Grip Bench Press", "muscle_group": "Chest", "difficulty": "Intermediate", "equipment_needed": "Barbell, Bench", "description": "Inner chest and triceps."},
            {"name": "Svend Press", "muscle_group": "Chest", "difficulty": "Beginner", "equipment_needed": "Weight Plates", "description": "Constant inner chest tension."},
            {"name": "Resistance Band Chest Press", "muscle_group": "Chest", "difficulty": "Beginner", "equipment_needed": "Resistance Band", "description": "Portable chest press."},
            {"name": "Floor Press", "muscle_group": "Chest", "difficulty": "Intermediate", "equipment_needed": "Barbell or Dumbbells", "description": "Partial ROM bench alternative."},
            {"name": "Chest Squeeze Press", "muscle_group": "Chest", "difficulty": "Beginner", "equipment_needed": "Dumbbells", "description": "Squeeze dumbbells together throughout."},
            {"name": "Low Cable Fly", "muscle_group": "Chest", "difficulty": "Beginner", "equipment_needed": "Cable Machine", "description": "Upper chest cable fly."},
            {"name": "High Cable Fly", "muscle_group": "Chest", "difficulty": "Beginner", "equipment_needed": "Cable Machine", "description": "Lower chest cable fly."},
            {"name": "Machine Chest Press", "muscle_group": "Chest", "difficulty": "Beginner", "equipment_needed": "Chest Press Machine", "description": "Beginner-friendly machine press."},
            # BACK (20)
            {"name": "Barbell Deadlift", "muscle_group": "Back", "difficulty": "Advanced", "equipment_needed": "Barbell", "description": "King of posterior chain exercises."},
            {"name": "Pull-Ups", "muscle_group": "Back", "difficulty": "Intermediate", "equipment_needed": "Pull-Up Bar", "description": "Bodyweight lat builder."},
            {"name": "Lat Pulldown", "muscle_group": "Back", "difficulty": "Beginner", "equipment_needed": "Cable Machine", "description": "Lat isolation pulldown."},
            {"name": "Barbell Bent-Over Row", "muscle_group": "Back", "difficulty": "Intermediate", "equipment_needed": "Barbell", "description": "Compound back thickness builder."},
            {"name": "Dumbbell Single-Arm Row", "muscle_group": "Back", "difficulty": "Beginner", "equipment_needed": "Dumbbell, Bench", "description": "Unilateral back development."},
            {"name": "Seated Cable Row", "muscle_group": "Back", "difficulty": "Beginner", "equipment_needed": "Cable Machine", "description": "Mid-back compound row."},
            {"name": "T-Bar Row", "muscle_group": "Back", "difficulty": "Intermediate", "equipment_needed": "T-Bar Machine or Barbell", "description": "Thick back builder."},
            {"name": "Face Pulls", "muscle_group": "Back", "difficulty": "Beginner", "equipment_needed": "Cable Machine, Rope", "description": "Rear delt and upper back health."},
            {"name": "Chest-Supported Row", "muscle_group": "Back", "difficulty": "Beginner", "equipment_needed": "Incline Bench, Dumbbells", "description": "Strict row with chest support."},
            {"name": "Inverted Row", "muscle_group": "Back", "difficulty": "Beginner", "equipment_needed": "Smith Machine or Bar", "description": "Bodyweight row progression."},
            {"name": "Straight-Arm Pulldown", "muscle_group": "Back", "difficulty": "Beginner", "equipment_needed": "Cable Machine", "description": "Lat isolation with straight arms."},
            {"name": "Meadows Row", "muscle_group": "Back", "difficulty": "Intermediate", "equipment_needed": "Barbell, Landmine", "description": "Unilateral landmine row."},
            {"name": "Renegade Row", "muscle_group": "Back", "difficulty": "Advanced", "equipment_needed": "Dumbbells", "description": "Row plus core stability combo."},
            {"name": "Trap Bar Deadlift", "muscle_group": "Back", "difficulty": "Intermediate", "equipment_needed": "Trap Bar", "description": "Spine-friendly deadlift variant."},
            {"name": "Romanian Deadlift", "muscle_group": "Back", "difficulty": "Intermediate", "equipment_needed": "Barbell or Dumbbells", "description": "Hamstring and lower back emphasis."},
            {"name": "Good Morning", "muscle_group": "Back", "difficulty": "Intermediate", "equipment_needed": "Barbell", "description": "Lower back and hamstring hinge."},
            {"name": "Wide-Grip Lat Pulldown", "muscle_group": "Back", "difficulty": "Beginner", "equipment_needed": "Cable Machine", "description": "Wider lat activation."},
            {"name": "Reverse-Grip Pulldown", "muscle_group": "Back", "difficulty": "Beginner", "equipment_needed": "Cable Machine", "description": "Lower lat emphasis pulldown."},
            {"name": "Rack Pull", "muscle_group": "Back", "difficulty": "Intermediate", "equipment_needed": "Barbell, Power Rack", "description": "Partial deadlift for upper back."},
            {"name": "Machine Row", "muscle_group": "Back", "difficulty": "Beginner", "equipment_needed": "Row Machine", "description": "Machine-based back row."},
            # LEGS (20)
            {"name": "Barbell Back Squat", "muscle_group": "Legs", "difficulty": "Advanced", "equipment_needed": "Barbell, Squat Rack", "description": "King of lower body movements."},
            {"name": "Front Squat", "muscle_group": "Legs", "difficulty": "Advanced", "equipment_needed": "Barbell, Squat Rack", "description": "Quad-dominant squat variant."},
            {"name": "Leg Press", "muscle_group": "Legs", "difficulty": "Beginner", "equipment_needed": "Leg Press Machine", "description": "Machine-based quad press."},
            {"name": "Bulgarian Split Squat", "muscle_group": "Legs", "difficulty": "Intermediate", "equipment_needed": "Dumbbells, Bench", "description": "Unilateral quad and glute focus."},
            {"name": "Lunges", "muscle_group": "Legs", "difficulty": "Beginner", "equipment_needed": "None or Dumbbells", "description": "Walking or stationary lunge."},
            {"name": "Romanian Deadlift Legs", "muscle_group": "Legs", "difficulty": "Intermediate", "equipment_needed": "Barbell or Dumbbells", "description": "Hamstring-dominant hinge."},
            {"name": "Leg Curl", "muscle_group": "Legs", "difficulty": "Beginner", "equipment_needed": "Leg Curl Machine", "description": "Hamstring isolation."},
            {"name": "Leg Extension", "muscle_group": "Legs", "difficulty": "Beginner", "equipment_needed": "Leg Extension Machine", "description": "Quad isolation."},
            {"name": "Glute Bridge", "muscle_group": "Legs", "difficulty": "Beginner", "equipment_needed": "None or Barbell", "description": "Glute isolation hip thrust."},
            {"name": "Hip Thrust", "muscle_group": "Legs", "difficulty": "Intermediate", "equipment_needed": "Barbell, Bench", "description": "Peak glute contraction."},
            {"name": "Step-Ups", "muscle_group": "Legs", "difficulty": "Beginner", "equipment_needed": "Box, Dumbbells", "description": "Unilateral leg press pattern."},
            {"name": "Goblet Squat", "muscle_group": "Legs", "difficulty": "Beginner", "equipment_needed": "Dumbbell or Kettlebell", "description": "Beginner-friendly squat pattern."},
            {"name": "Sumo Squat", "muscle_group": "Legs", "difficulty": "Beginner", "equipment_needed": "Dumbbell or Barbell", "description": "Wide stance inner thigh activation."},
            {"name": "Standing Calf Raise", "muscle_group": "Legs", "difficulty": "Beginner", "equipment_needed": "Calf Raise Machine or Step", "description": "Calf hypertrophy."},
            {"name": "Seated Calf Raise", "muscle_group": "Legs", "difficulty": "Beginner", "equipment_needed": "Seated Calf Raise Machine", "description": "Soleus-focused calf exercise."},
            {"name": "Hack Squat", "muscle_group": "Legs", "difficulty": "Intermediate", "equipment_needed": "Hack Squat Machine", "description": "Quad-focused machine squat."},
            {"name": "Wall Sit", "muscle_group": "Legs", "difficulty": "Beginner", "equipment_needed": "None", "description": "Isometric quad endurance."},
            {"name": "Box Jump", "muscle_group": "Legs", "difficulty": "Intermediate", "equipment_needed": "Plyo Box", "description": "Explosive lower body power."},
            {"name": "Kettlebell Swing", "muscle_group": "Legs", "difficulty": "Intermediate", "equipment_needed": "Kettlebell", "description": "Hip hinge power movement."},
            {"name": "Nordic Hamstring Curl", "muscle_group": "Legs", "difficulty": "Advanced", "equipment_needed": "Partner or Anchor", "description": "Eccentric hamstring strengthener."},
            # SHOULDERS (20)
            {"name": "Barbell Overhead Press", "muscle_group": "Shoulders", "difficulty": "Intermediate", "equipment_needed": "Barbell", "description": "Compound shoulder press."},
            {"name": "Dumbbell Shoulder Press", "muscle_group": "Shoulders", "difficulty": "Beginner", "equipment_needed": "Dumbbells", "description": "Seated or standing shoulder press."},
            {"name": "Lateral Raises", "muscle_group": "Shoulders", "difficulty": "Beginner", "equipment_needed": "Dumbbells", "description": "Medial delt isolation."},
            {"name": "Front Raises", "muscle_group": "Shoulders", "difficulty": "Beginner", "equipment_needed": "Dumbbells or Barbell", "description": "Anterior delt raise."},
            {"name": "Rear Delt Fly", "muscle_group": "Shoulders", "difficulty": "Beginner", "equipment_needed": "Dumbbells or Cable", "description": "Posterior delt isolation."},
            {"name": "Arnold Press", "muscle_group": "Shoulders", "difficulty": "Intermediate", "equipment_needed": "Dumbbells", "description": "Rotational shoulder press."},
            {"name": "Cable Lateral Raise", "muscle_group": "Shoulders", "difficulty": "Beginner", "equipment_needed": "Cable Machine", "description": "Constant tension lateral raise."},
            {"name": "Upright Row", "muscle_group": "Shoulders", "difficulty": "Intermediate", "equipment_needed": "Barbell or Dumbbells", "description": "Trap and delt compound."},
            {"name": "Machine Shoulder Press", "muscle_group": "Shoulders", "difficulty": "Beginner", "equipment_needed": "Shoulder Press Machine", "description": "Guided shoulder press."},
            {"name": "Pike Push-Up", "muscle_group": "Shoulders", "difficulty": "Beginner", "equipment_needed": "None", "description": "Bodyweight shoulder press."},
            {"name": "Handstand Push-Up", "muscle_group": "Shoulders", "difficulty": "Advanced", "equipment_needed": "Wall", "description": "Inverted bodyweight press."},
            {"name": "Shrugs", "muscle_group": "Shoulders", "difficulty": "Beginner", "equipment_needed": "Barbell or Dumbbells", "description": "Trapezius isolation."},
            {"name": "Band Pull-Apart", "muscle_group": "Shoulders", "difficulty": "Beginner", "equipment_needed": "Resistance Band", "description": "Rear delt warm-up."},
            {"name": "Seated Dumbbell Press", "muscle_group": "Shoulders", "difficulty": "Beginner", "equipment_needed": "Dumbbells, Bench", "description": "Seated shoulder stability press."},
            {"name": "Landmine Press Shoulder", "muscle_group": "Shoulders", "difficulty": "Intermediate", "equipment_needed": "Barbell, Landmine", "description": "Shoulder-friendly press angle."},
            {"name": "Push Press", "muscle_group": "Shoulders", "difficulty": "Intermediate", "equipment_needed": "Barbell", "description": "Leg-assisted overhead press."},
            {"name": "Trap Bar Shrug", "muscle_group": "Shoulders", "difficulty": "Beginner", "equipment_needed": "Trap Bar", "description": "Neutral grip trap shrug."},
            {"name": "Behind-the-Neck Press", "muscle_group": "Shoulders", "difficulty": "Advanced", "equipment_needed": "Barbell", "description": "Lateral delt press variation."},
            {"name": "Cross-Body Cable Lateral Raise", "muscle_group": "Shoulders", "difficulty": "Beginner", "equipment_needed": "Cable Machine", "description": "Cross-body medial delt raise."},
            {"name": "Y-T-W Raise", "muscle_group": "Shoulders", "difficulty": "Beginner", "equipment_needed": "Dumbbells", "description": "Rotator cuff and rear delt."},
            # BICEPS (20)
            {"name": "Barbell Curl", "muscle_group": "Biceps", "difficulty": "Beginner", "equipment_needed": "Barbell", "description": "Classic bicep curl."},
            {"name": "Dumbbell Curl", "muscle_group": "Biceps", "difficulty": "Beginner", "equipment_needed": "Dumbbells", "description": "Alternating or simultaneous curl."},
            {"name": "Hammer Curl", "muscle_group": "Biceps", "difficulty": "Beginner", "equipment_needed": "Dumbbells", "description": "Brachialis and brachioradialis focus."},
            {"name": "Incline Dumbbell Curl", "muscle_group": "Biceps", "difficulty": "Intermediate", "equipment_needed": "Dumbbells, Incline Bench", "description": "Stretched position bicep curl."},
            {"name": "Concentration Curl", "muscle_group": "Biceps", "difficulty": "Beginner", "equipment_needed": "Dumbbell", "description": "Peak contraction isolation."},
            {"name": "Cable Curl", "muscle_group": "Biceps", "difficulty": "Beginner", "equipment_needed": "Cable Machine", "description": "Constant tension curl."},
            {"name": "Preacher Curl", "muscle_group": "Biceps", "difficulty": "Intermediate", "equipment_needed": "EZ Bar, Preacher Bench", "description": "Strict form isolation curl."},
            {"name": "EZ Bar Curl", "muscle_group": "Biceps", "difficulty": "Beginner", "equipment_needed": "EZ Bar", "description": "Wrist-friendly bicep curl."},
            {"name": "Spider Curl", "muscle_group": "Biceps", "difficulty": "Intermediate", "equipment_needed": "Barbell or Dumbbells, Incline Bench", "description": "Steep angle curl for peak."},
            {"name": "Reverse Curl", "muscle_group": "Biceps", "difficulty": "Beginner", "equipment_needed": "Barbell or EZ Bar", "description": "Forearm and brachialis overhand curl."},
            {"name": "Zottman Curl", "muscle_group": "Biceps", "difficulty": "Intermediate", "equipment_needed": "Dumbbells", "description": "Supinate up, pronate down."},
            {"name": "Cross-Body Hammer Curl", "muscle_group": "Biceps", "difficulty": "Beginner", "equipment_needed": "Dumbbells", "description": "Cross-body brachialis focus."},
            {"name": "Cable Hammer Curl", "muscle_group": "Biceps", "difficulty": "Beginner", "equipment_needed": "Cable Machine, Rope", "description": "Cable neutral grip curl."},
            {"name": "High Cable Curl", "muscle_group": "Biceps", "difficulty": "Beginner", "equipment_needed": "Cable Machine", "description": "Arms at shoulder height curl."},
            {"name": "21s Curl", "muscle_group": "Biceps", "difficulty": "Intermediate", "equipment_needed": "Barbell or Dumbbells", "description": "7 lower, 7 upper, 7 full reps."},
            {"name": "Rope Cable Curl", "muscle_group": "Biceps", "difficulty": "Beginner", "equipment_needed": "Cable Machine, Rope", "description": "Rope attachment bicep curl."},
            {"name": "Machine Curl", "muscle_group": "Biceps", "difficulty": "Beginner", "equipment_needed": "Bicep Curl Machine", "description": "Guided machine bicep curl."},
            {"name": "Waiter Curl", "muscle_group": "Biceps", "difficulty": "Beginner", "equipment_needed": "Dumbbell or Plate", "description": "Long head isolation curl."},
            {"name": "TRX Curl", "muscle_group": "Biceps", "difficulty": "Intermediate", "equipment_needed": "TRX Straps", "description": "Suspension bodyweight curl."},
            {"name": "Chin-Up", "muscle_group": "Biceps", "difficulty": "Intermediate", "equipment_needed": "Pull-Up Bar", "description": "Supinated grip compound curl."},
            # TRICEPS (20)
            {"name": "Close-Grip Bench Press", "muscle_group": "Triceps", "difficulty": "Intermediate", "equipment_needed": "Barbell, Bench", "description": "Compound tricep press."},
            {"name": "Tricep Dips", "muscle_group": "Triceps", "difficulty": "Intermediate", "equipment_needed": "Dip Bars or Bench", "description": "Bodyweight tricep compound."},
            {"name": "Skull Crushers", "muscle_group": "Triceps", "difficulty": "Intermediate", "equipment_needed": "EZ Bar or Barbell, Bench", "description": "Long head tricep isolation."},
            {"name": "Tricep Pushdown", "muscle_group": "Triceps", "difficulty": "Beginner", "equipment_needed": "Cable Machine, Bar", "description": "Classic cable tricep exercise."},
            {"name": "Rope Pushdown", "muscle_group": "Triceps", "difficulty": "Beginner", "equipment_needed": "Cable Machine, Rope", "description": "Rope attachment pushdown."},
            {"name": "Overhead Tricep Extension", "muscle_group": "Triceps", "difficulty": "Beginner", "equipment_needed": "Dumbbell or Cable", "description": "Long head stretch extension."},
            {"name": "Diamond Push-Ups Triceps", "muscle_group": "Triceps", "difficulty": "Intermediate", "equipment_needed": "None", "description": "Bodyweight tricep isolation."},
            {"name": "JM Press", "muscle_group": "Triceps", "difficulty": "Advanced", "equipment_needed": "Barbell, Bench", "description": "Hybrid press and skull crusher."},
            {"name": "Tate Press", "muscle_group": "Triceps", "difficulty": "Intermediate", "equipment_needed": "Dumbbells, Bench", "description": "Dumbbell tricep isolation."},
            {"name": "Single-Arm Overhead Tricep Extension", "muscle_group": "Triceps", "difficulty": "Beginner", "equipment_needed": "Dumbbell", "description": "Unilateral tricep stretch."},
            {"name": "Reverse-Grip Pushdown", "muscle_group": "Triceps", "difficulty": "Beginner", "equipment_needed": "Cable Machine", "description": "Medial head emphasis pushdown."},
            {"name": "Lying Tricep Extension", "muscle_group": "Triceps", "difficulty": "Beginner", "equipment_needed": "Dumbbells", "description": "Floor or bench extension."},
            {"name": "Bench Dips", "muscle_group": "Triceps", "difficulty": "Beginner", "equipment_needed": "Bench", "description": "Bodyweight bench tricep dip."},
            {"name": "Kickbacks", "muscle_group": "Triceps", "difficulty": "Beginner", "equipment_needed": "Dumbbell", "description": "Isolation tricep kickback."},
            {"name": "Cable Kickback", "muscle_group": "Triceps", "difficulty": "Beginner", "equipment_needed": "Cable Machine", "description": "Constant tension kickback."},
            {"name": "Smith Machine Tricep Press", "muscle_group": "Triceps", "difficulty": "Beginner", "equipment_needed": "Smith Machine", "description": "Guided narrow grip press."},
            {"name": "EZ Bar Overhead Extension", "muscle_group": "Triceps", "difficulty": "Intermediate", "equipment_needed": "EZ Bar", "description": "EZ bar long head extension."},
            {"name": "Machine Tricep Dip", "muscle_group": "Triceps", "difficulty": "Beginner", "equipment_needed": "Assisted Dip Machine", "description": "Assisted machine dip."},
            {"name": "Band Pushdown", "muscle_group": "Triceps", "difficulty": "Beginner", "equipment_needed": "Resistance Band", "description": "Band-based tricep pushdown."},
            {"name": "Floor Tricep Extension", "muscle_group": "Triceps", "difficulty": "Beginner", "equipment_needed": "Dumbbells", "description": "Floor-based skull crusher."},
            # CORE (20)
            {"name": "Plank", "muscle_group": "Core", "difficulty": "Beginner", "equipment_needed": "None", "description": "Isometric core stability."},
            {"name": "Crunches", "muscle_group": "Core", "difficulty": "Beginner", "equipment_needed": "None", "description": "Basic upper ab crunch."},
            {"name": "Bicycle Crunches", "muscle_group": "Core", "difficulty": "Beginner", "equipment_needed": "None", "description": "Oblique and rectus abdominis."},
            {"name": "Leg Raises", "muscle_group": "Core", "difficulty": "Intermediate", "equipment_needed": "None or Pull-Up Bar", "description": "Lower ab focus."},
            {"name": "Russian Twists", "muscle_group": "Core", "difficulty": "Beginner", "equipment_needed": "None or Weight Plate", "description": "Oblique rotational exercise."},
            {"name": "Ab Wheel Rollout", "muscle_group": "Core", "difficulty": "Advanced", "equipment_needed": "Ab Wheel", "description": "Extreme core stability."},
            {"name": "Cable Crunch", "muscle_group": "Core", "difficulty": "Beginner", "equipment_needed": "Cable Machine", "description": "Weighted cable abs."},
            {"name": "Hanging Knee Raise", "muscle_group": "Core", "difficulty": "Intermediate", "equipment_needed": "Pull-Up Bar", "description": "Hip flexor and lower ab raise."},
            {"name": "Toe-to-Bar", "muscle_group": "Core", "difficulty": "Advanced", "equipment_needed": "Pull-Up Bar", "description": "Full leg raise to bar."},
            {"name": "Mountain Climbers", "muscle_group": "Core", "difficulty": "Beginner", "equipment_needed": "None", "description": "Dynamic core and cardio."},
            {"name": "Side Plank", "muscle_group": "Core", "difficulty": "Beginner", "equipment_needed": "None", "description": "Lateral core stability."},
            {"name": "Dead Bug", "muscle_group": "Core", "difficulty": "Beginner", "equipment_needed": "None", "description": "Spine-safe anti-extension."},
            {"name": "Bird Dog", "muscle_group": "Core", "difficulty": "Beginner", "equipment_needed": "None", "description": "Core and balance coordination."},
            {"name": "Hollow Body Hold", "muscle_group": "Core", "difficulty": "Intermediate", "equipment_needed": "None", "description": "Gymnastic core contraction."},
            {"name": "V-Ups", "muscle_group": "Core", "difficulty": "Intermediate", "equipment_needed": "None", "description": "Full abdominal contraction."},
            {"name": "Dragon Flag", "muscle_group": "Core", "difficulty": "Advanced", "equipment_needed": "Bench", "description": "Advanced core exercise."},
            {"name": "Pallof Press", "muscle_group": "Core", "difficulty": "Beginner", "equipment_needed": "Cable Machine or Band", "description": "Anti-rotation core press."},
            {"name": "Wood Chop", "muscle_group": "Core", "difficulty": "Beginner", "equipment_needed": "Cable Machine or Medicine Ball", "description": "Rotational power exercise."},
            {"name": "Sit-Ups", "muscle_group": "Core", "difficulty": "Beginner", "equipment_needed": "None", "description": "Classic full range ab exercise."},
            {"name": "Flutter Kicks", "muscle_group": "Core", "difficulty": "Beginner", "equipment_needed": "None", "description": "Alternating leg lower ab."},
            # CARDIO (20)
            {"name": "Treadmill Run", "muscle_group": "Cardio", "difficulty": "Beginner", "equipment_needed": "Treadmill", "description": "Steady state cardio."},
            {"name": "Cycling", "muscle_group": "Cardio", "difficulty": "Beginner", "equipment_needed": "Stationary Bike", "description": "Low impact cardio."},
            {"name": "Rowing Machine", "muscle_group": "Cardio", "difficulty": "Intermediate", "equipment_needed": "Rowing Machine", "description": "Full body cardio."},
            {"name": "Jump Rope", "muscle_group": "Cardio", "difficulty": "Intermediate", "equipment_needed": "Jump Rope", "description": "High intensity skipping."},
            {"name": "Elliptical", "muscle_group": "Cardio", "difficulty": "Beginner", "equipment_needed": "Elliptical Machine", "description": "Low impact full body cardio."},
            {"name": "Stair Climber", "muscle_group": "Cardio", "difficulty": "Intermediate", "equipment_needed": "Stair Climber Machine", "description": "Glute and cardio combo."},
            {"name": "Burpees", "muscle_group": "Cardio", "difficulty": "Intermediate", "equipment_needed": "None", "description": "Full body HIIT staple."},
            {"name": "Sprint Intervals", "muscle_group": "Cardio", "difficulty": "Advanced", "equipment_needed": "Treadmill or Track", "description": "High intensity speed work."},
            {"name": "Battle Ropes", "muscle_group": "Cardio", "difficulty": "Intermediate", "equipment_needed": "Battle Ropes", "description": "Upper body conditioning."},
            {"name": "Box Jumps Cardio", "muscle_group": "Cardio", "difficulty": "Intermediate", "equipment_needed": "Plyo Box", "description": "Explosive plyometric cardio."},
            {"name": "Swimming", "muscle_group": "Cardio", "difficulty": "Beginner", "equipment_needed": "Pool", "description": "Full body aquatic cardio."},
            {"name": "High Knees", "muscle_group": "Cardio", "difficulty": "Beginner", "equipment_needed": "None", "description": "Running in place high knees."},
            {"name": "Jumping Jacks", "muscle_group": "Cardio", "difficulty": "Beginner", "equipment_needed": "None", "description": "Classic warm-up cardio."},
            {"name": "Assault Bike", "muscle_group": "Cardio", "difficulty": "Advanced", "equipment_needed": "Assault Bike", "description": "High intensity fan bike."},
            {"name": "Sled Push", "muscle_group": "Cardio", "difficulty": "Advanced", "equipment_needed": "Sled, Weights", "description": "Loaded sled conditioning."},
            {"name": "Prowler Push", "muscle_group": "Cardio", "difficulty": "Advanced", "equipment_needed": "Prowler Sled", "description": "Metabolic conditioning sled."},
            {"name": "Ski Erg", "muscle_group": "Cardio", "difficulty": "Intermediate", "equipment_needed": "Ski Erg Machine", "description": "Upper body pulling cardio."},
            {"name": "Incline Walk", "muscle_group": "Cardio", "difficulty": "Beginner", "equipment_needed": "Treadmill", "description": "Low impact fat burn walk."},
            {"name": "Bear Crawl", "muscle_group": "Cardio", "difficulty": "Intermediate", "equipment_needed": "None", "description": "Quadruped locomotion drill."},
            {"name": "Farmer Walk", "muscle_group": "Cardio", "difficulty": "Beginner", "equipment_needed": "Dumbbells or Trap Bar", "description": "Loaded carry conditioning."},
            # FULL BODY (20)
            {"name": "Power Clean", "muscle_group": "Full Body", "difficulty": "Advanced", "equipment_needed": "Barbell", "description": "Olympic lift posterior chain."},
            {"name": "Thruster", "muscle_group": "Full Body", "difficulty": "Intermediate", "equipment_needed": "Barbell or Dumbbells", "description": "Squat to press combo."},
            {"name": "Clean and Press", "muscle_group": "Full Body", "difficulty": "Advanced", "equipment_needed": "Barbell or Dumbbells", "description": "Full body power and press."},
            {"name": "Turkish Get-Up", "muscle_group": "Full Body", "difficulty": "Advanced", "equipment_needed": "Kettlebell", "description": "Complex mobility and strength."},
            {"name": "Man Maker", "muscle_group": "Full Body", "difficulty": "Advanced", "equipment_needed": "Dumbbells", "description": "Burpee plus row plus press combo."},
            {"name": "Squat to Press", "muscle_group": "Full Body", "difficulty": "Beginner", "equipment_needed": "Dumbbells", "description": "Goblet squat into shoulder press."},
            {"name": "Deadlift High Pull", "muscle_group": "Full Body", "difficulty": "Intermediate", "equipment_needed": "Barbell or Dumbbells", "description": "Explosive deadlift and row."},
            {"name": "Sandbag Carry", "muscle_group": "Full Body", "difficulty": "Intermediate", "equipment_needed": "Sandbag", "description": "Loaded carry for conditioning."},
            {"name": "Devil Press", "muscle_group": "Full Body", "difficulty": "Advanced", "equipment_needed": "Dumbbells", "description": "Burpee snatch hybrid."},
            {"name": "Wall Ball", "muscle_group": "Full Body", "difficulty": "Intermediate", "equipment_needed": "Medicine Ball, Wall", "description": "Squat to overhead throw."},
            {"name": "Tire Flip", "muscle_group": "Full Body", "difficulty": "Advanced", "equipment_needed": "Heavy Tire", "description": "Full body explosive flip."},
            {"name": "Bear Complex", "muscle_group": "Full Body", "difficulty": "Advanced", "equipment_needed": "Barbell", "description": "7-movement barbell complex."},
            {"name": "Pull-Up to Dip", "muscle_group": "Full Body", "difficulty": "Advanced", "equipment_needed": "Pull-Up/Dip Station", "description": "Upper body push-pull superset."},
            {"name": "Dumbbell Complex", "muscle_group": "Full Body", "difficulty": "Intermediate", "equipment_needed": "Dumbbells", "description": "Row plus curl plus press sequence."},
            {"name": "Barbell Complex", "muscle_group": "Full Body", "difficulty": "Advanced", "equipment_needed": "Barbell", "description": "Multi-movement barbell series."},
            {"name": "Atlas Stone Lift", "muscle_group": "Full Body", "difficulty": "Advanced", "equipment_needed": "Atlas Stone", "description": "Strongman stone loading."},
            {"name": "Medball Slam", "muscle_group": "Full Body", "difficulty": "Beginner", "equipment_needed": "Medicine Ball", "description": "Full body power slam."},
            {"name": "Overhead Squat", "muscle_group": "Full Body", "difficulty": "Advanced", "equipment_needed": "Barbell", "description": "Squat with barbell overhead."},
            {"name": "Single-Leg Deadlift to Press", "muscle_group": "Full Body", "difficulty": "Advanced", "equipment_needed": "Dumbbells", "description": "Balance and full body chain."},
            {"name": "Plank Row", "muscle_group": "Full Body", "difficulty": "Intermediate", "equipment_needed": "Dumbbells", "description": "Plank with alternating row."},
        ]

        created = 0
        for ex in exercises:
            obj, was_created = Exercise.objects.get_or_create(
                name=ex["name"],
                defaults={
                    "muscle_group": ex["muscle_group"],
                    "difficulty": ex["difficulty"],
                    "equipment_needed": ex["equipment_needed"],
                    "description": ex["description"],
                    "video_url": "",
                }
            )
            if was_created:
                created += 1

        self.stdout.write(self.style.SUCCESS(
            f"Seeded {created} new workout exercises ({len(exercises)} total checked)"
        ))
