# Generated by Django 6.0.1 on 2026-02-21 10:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('waist_cm', models.FloatField(blank=True, null=True)),
                ('chest_cm', models.FloatField(blank=True, null=True)),
                ('arms_cm', models.FloatField(blank=True, null=True)),
                ('thighs_cm', models.FloatField(blank=True, null=True)),
                ('photo_front_b64', models.TextField(blank=True)),
                ('photo_side_b64', models.TextField(blank=True)),
                ('photo_back_b64', models.TextField(blank=True)),
                ('ai_analysis', models.TextField(blank=True)),
                ('body_fat_estimate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('water_ml', models.IntegerField(default=0)),
                ('water_goal_ml', models.IntegerField(default=2500)),
                ('steps', models.IntegerField(default=0)),
                ('step_goal', models.IntegerField(default=8000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
