# Generated by Django 6.0.1 on 2026-02-21 20:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_bodyprogressentry_dailyactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyprogressentry',
            name='photo_back',
            field=models.ImageField(blank=True, null=True, upload_to='body_scans/'),
        ),
        migrations.AddField(
            model_name='bodyprogressentry',
            name='photo_front',
            field=models.ImageField(blank=True, null=True, upload_to='body_scans/'),
        ),
        migrations.AddField(
            model_name='bodyprogressentry',
            name='photo_side',
            field=models.ImageField(blank=True, null=True, upload_to='body_scans/'),
        ),
        migrations.CreateModel(
            name='UserActivityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('activity_type', models.CharField(choices=[('idle', 'Idle'), ('walking', 'Walking'), ('working_out', 'Working Out')], default='idle', max_length=20)),
                ('steps_live', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('workout_plan_name', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('set_number', models.IntegerField(default=1)),
                ('reps', models.IntegerField()),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('effectiveness', models.CharField(choices=[('Too Easy', 'Too Easy'), ('Just Right', 'Just Right'), ('Very Hard', 'Very Hard')], max_length=20)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
