# Generated by Django 6.0.1 on 2026-03-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_bodyprogressentry_photo_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsetlog',
            name='set_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Warm-up', 'Warm-up'), ('Drop Set', 'Drop Set')], default='Regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='workoutsetlog',
            name='effectiveness',
            field=models.CharField(choices=[('Too Easy', 'Too Easy'), ('Easy', 'Easy'), ('Just Right', 'Just Right'), ('Hard', 'Hard'), ('Too Hard', 'Too Hard')], max_length=20),
        ),
    ]
