# Generated by Django 6.0.1 on 2026-03-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_workoutsetlog_set_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsetlog',
            name='treadmill_incline',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workoutsetlog',
            name='treadmill_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
