# Generated by Django 6.0.1 on 2026-03-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_workoutsetlog_treadmill_incline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsetlog',
            name='pose_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutsetlog',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
