# Generated by Django 6.0.1 on 2026-02-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='is_community',
            field=models.BooleanField(default=False),
        ),
    ]
