# Generated by Django 6.0.1 on 2026-02-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0003_dailyquestcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
    ]
