# Generated by Django 6.0.1 on 2026-02-16 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_remove_waterlog_user_dietplan_fooditem_meal_mealitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=15)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_schedules', to=settings.AUTH_USER_MODEL)),
                ('diet_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutrition.dietplan')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('recruit', 'day_of_week')},
            },
        ),
    ]
