# Generated by Django 6.0.1 on 2026-03-30 08:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_fooditem_is_global_alter_dietplan_coach_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplement_name', models.CharField(max_length=100)),
                ('target_time', models.TimeField(blank=True, null=True)),
                ('is_taken', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'supplement_name', 'date')},
            },
        ),
    ]
