# Generated by Django 6.0.1 on 2026-02-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('core', 'Core'), ('cardio', 'Cardio'), ('full_body', 'Full Body')], max_length=20)),
                ('equipment', models.CharField(choices=[('none', 'Bodyweight'), ('dumbbell', 'Dumbbell'), ('barbell', 'Barbell'), ('kettlebell', 'Kettlebell'), ('machine', 'Machine'), ('cables', 'Cables')], default='none', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('image_url', models.URLField(blank=True, help_text='Link to an image of the exercise', null=True)),
                ('video_url', models.URLField(blank=True, help_text='YouTube link for demonstration', null=True)),
            ],
        ),
    ]
