# Generated by Django 6.0.1 on 2026-02-09 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('muscle_group', models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Legs', 'Legs'), ('Shoulders', 'Shoulders'), ('Biceps', 'Biceps'), ('Triceps', 'Triceps'), ('Core', 'Core'), ('Cardio', 'Cardio'), ('Full Body', 'Full Body')], max_length=50)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('equipment_needed', models.CharField(default='None', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='workoutplan',
            old_name='plan_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='user',
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='coach',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(default=3)),
                ('reps', models.CharField(default='10-12', max_length=20)),
                ('rest_time', models.IntegerField(default=60, help_text='Seconds')),
                ('order', models.IntegerField(default=1)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workouts.workoutplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
