from django.core.management.base import BaseCommand
from exercises.models import Exercise

EXERCISES = [
    # ── CHEST (20) ─────────────────────────────────────────────────────────────
    ("Push-Up", "chest", "none", "beginner",
     "Classic bodyweight push targeting the chest and triceps.",
     "https://www.youtube.com/results?search_query=push+up+proper+form+tutorial"),
    ("Wide Push-Up", "chest", "none", "beginner",
     "Wide-grip push-up that shifts emphasis onto the outer chest.",
     "https://www.youtube.com/results?search_query=wide+grip+push+up+tutorial"),
    ("Incline Push-Up", "chest", "none", "beginner",
     "Hands-elevated push-up targeting the lower chest.",
     "https://www.youtube.com/results?search_query=incline+push+up+tutorial"),
    ("Decline Push-Up", "chest", "none", "intermediate",
     "Feet-elevated push-up that hits the upper chest harder.",
     "https://www.youtube.com/results?search_query=decline+push+up+tutorial"),
    ("Diamond Push-Up", "chest", "none", "intermediate",
     "Narrow diamond hand position that hammers the inner chest and triceps.",
     "https://www.youtube.com/results?search_query=diamond+push+up+tutorial"),
    ("Dumbbell Bench Press", "chest", "dumbbell", "intermediate",
     "Flat bench press with dumbbells for balanced full chest development.",
     "https://www.youtube.com/results?search_query=dumbbell+bench+press+tutorial"),
    ("Incline Dumbbell Press", "chest", "dumbbell", "intermediate",
     "Angled press that zones in on the upper chest.",
     "https://www.youtube.com/results?search_query=incline+dumbbell+press+tutorial"),
    ("Decline Dumbbell Press", "chest", "dumbbell", "intermediate",
     "Downward-angled press for lower chest development.",
     "https://www.youtube.com/results?search_query=decline+dumbbell+press+tutorial"),
    ("Dumbbell Flye", "chest", "dumbbell", "intermediate",
     "Wide-arc isolation movement giving the chest a deep stretch.",
     "https://www.youtube.com/results?search_query=dumbbell+flye+chest+tutorial"),
    ("Incline Dumbbell Flye", "chest", "dumbbell", "intermediate",
     "Elevated flye specifically targeting the upper chest.",
     "https://www.youtube.com/results?search_query=incline+dumbbell+flye+tutorial"),
    ("Barbell Bench Press", "chest", "barbell", "intermediate",
     "The classic compound press for building overall chest mass.",
     "https://www.youtube.com/results?search_query=barbell+bench+press+form+tutorial"),
    ("Incline Barbell Press", "chest", "barbell", "intermediate",
     "Barbell press at an upward angle for upper chest emphasis.",
     "https://www.youtube.com/results?search_query=incline+barbell+press+tutorial"),
    ("Cable Crossover", "chest", "cables", "intermediate",
     "Cable-based crossover for peak mid-chest contraction.",
     "https://www.youtube.com/results?search_query=cable+crossover+chest+tutorial"),
    ("Low-to-High Cable Fly", "chest", "cables", "intermediate",
     "Upward cable fly that targets the upper chest.",
     "https://www.youtube.com/results?search_query=low+to+high+cable+fly+tutorial"),
    ("High-to-Low Cable Fly", "chest", "cables", "intermediate",
     "Downward cable fly for developing the lower chest.",
     "https://www.youtube.com/results?search_query=high+to+low+cable+fly+tutorial"),
    ("Chest Dip", "chest", "none", "intermediate",
     "Forward-lean dip that shifts the load to the chest.",
     "https://www.youtube.com/results?search_query=chest+dips+tutorial"),
    ("Machine Chest Press", "chest", "machine", "beginner",
     "Guided press machine for safe, isolated chest training.",
     "https://www.youtube.com/results?search_query=machine+chest+press+tutorial"),
    ("Pec Deck", "chest", "machine", "beginner",
     "Machine fly that isolates the pectoral muscles.",
     "https://www.youtube.com/results?search_query=pec+deck+fly+tutorial"),
    ("Landmine Press", "chest", "barbell", "intermediate",
     "Angled barbell press for functional chest and shoulder development.",
     "https://www.youtube.com/results?search_query=landmine+press+chest+tutorial"),
    ("Svend Press", "chest", "none", "beginner",
     "Plate-squeezing press that emphasises inner chest contraction.",
     "https://www.youtube.com/results?search_query=svend+press+tutorial"),

    # ── BACK (20) ──────────────────────────────────────────────────────────────
    ("Pull-Up", "back", "none", "intermediate",
     "Overhand pull-up building upper back width and strength.",
     "https://www.youtube.com/results?search_query=pull+up+proper+form+tutorial"),
    ("Chin-Up", "back", "none", "intermediate",
     "Underhand pull-up that emphasises the biceps and lower lats.",
     "https://www.youtube.com/results?search_query=chin+up+tutorial+form"),
    ("Inverted Row", "back", "none", "beginner",
     "Horizontal pull targeting the mid-back and rhomboids.",
     "https://www.youtube.com/results?search_query=inverted+row+tutorial"),
    ("Superman", "back", "none", "beginner",
     "Floor back extension that strengthens the spinal erectors.",
     "https://www.youtube.com/results?search_query=superman+exercise+back+tutorial"),
    ("Dumbbell Row", "back", "dumbbell", "beginner",
     "Single-arm row for unilateral lat and mid-back development.",
     "https://www.youtube.com/results?search_query=single+arm+dumbbell+row+tutorial"),
    ("Bent-Over Dumbbell Row", "back", "dumbbell", "intermediate",
     "Bilateral dumbbell row targeting the entire back.",
     "https://www.youtube.com/results?search_query=bent+over+dumbbell+row+tutorial"),
    ("Chest-Supported Row", "back", "dumbbell", "beginner",
     "Incline bench row that removes lower back involvement.",
     "https://www.youtube.com/results?search_query=chest+supported+row+tutorial"),
    ("Barbell Row", "back", "barbell", "intermediate",
     "Classic compound row for building overall back thickness.",
     "https://www.youtube.com/results?search_query=barbell+row+form+tutorial"),
    ("Pendlay Row", "back", "barbell", "intermediate",
     "Explosive barbell row from the floor for power development.",
     "https://www.youtube.com/results?search_query=pendlay+row+tutorial"),
    ("T-Bar Row", "back", "barbell", "intermediate",
     "Close-grip row for dense mid-back thickness.",
     "https://www.youtube.com/results?search_query=t+bar+row+tutorial"),
    ("Cable Seated Row", "back", "cables", "beginner",
     "Seated cable pull for mid-back and lower lat development.",
     "https://www.youtube.com/results?search_query=seated+cable+row+tutorial"),
    ("Lat Pulldown", "back", "cables", "beginner",
     "Cable pull from overhead building lat width.",
     "https://www.youtube.com/results?search_query=lat+pulldown+tutorial+form"),
    ("Wide-Grip Pulldown", "back", "cables", "beginner",
     "Wide-grip pulldown that emphasises upper lat width.",
     "https://www.youtube.com/results?search_query=wide+grip+lat+pulldown+tutorial"),
    ("Straight-Arm Pulldown", "back", "cables", "beginner",
     "Isolated lat activation through a full straight-arm range.",
     "https://www.youtube.com/results?search_query=straight+arm+pulldown+tutorial"),
    ("Deadlift", "back", "barbell", "intermediate",
     "Full-body compound lift anchored in the posterior chain.",
     "https://www.youtube.com/results?search_query=deadlift+proper+form+tutorial"),
    ("Romanian Deadlift", "back", "barbell", "intermediate",
     "Hip-hinge movement targeting hamstrings and lower back.",
     "https://www.youtube.com/results?search_query=romanian+deadlift+tutorial"),
    ("Good Morning", "back", "barbell", "intermediate",
     "Barbell hip-hinge for lower back and hamstring strength.",
     "https://www.youtube.com/results?search_query=good+morning+exercise+tutorial"),
    ("Hyperextension", "back", "none", "beginner",
     "Back extension on a glute-ham developer for spinal erectors.",
     "https://www.youtube.com/results?search_query=hyperextension+back+exercise+tutorial"),
    ("Face Pull", "back", "cables", "beginner",
     "Rope pull targeting the rear delts and rotator cuff health.",
     "https://www.youtube.com/results?search_query=face+pull+exercise+tutorial"),
    ("Meadows Row", "back", "barbell", "expert",
     "Landmine-based row for a unique upper-back stimulus.",
     "https://www.youtube.com/results?search_query=meadows+row+tutorial"),

    # ── LEGS (20) ──────────────────────────────────────────────────────────────
    ("Bodyweight Squat", "legs", "none", "beginner",
     "Fundamental squat pattern for overall lower-body strength.",
     "https://www.youtube.com/results?search_query=bodyweight+squat+proper+form+tutorial"),
    ("Goblet Squat", "legs", "dumbbell", "beginner",
     "Front-loaded squat improving depth, posture, and technique.",
     "https://www.youtube.com/results?search_query=goblet+squat+tutorial"),
    ("Sumo Squat", "legs", "dumbbell", "beginner",
     "Wide-stance squat emphasising the inner thighs and glutes.",
     "https://www.youtube.com/results?search_query=sumo+squat+tutorial"),
    ("Bulgarian Split Squat", "legs", "dumbbell", "intermediate",
     "Single-leg squat for quad and glute development.",
     "https://www.youtube.com/results?search_query=bulgarian+split+squat+tutorial"),
    ("Lunge", "legs", "none", "beginner",
     "Classic stepping movement for quads, hamstrings, and glutes.",
     "https://www.youtube.com/results?search_query=lunge+proper+form+tutorial"),
    ("Walking Lunge", "legs", "dumbbell", "beginner",
     "Dynamic forward lunge for functional leg strength.",
     "https://www.youtube.com/results?search_query=walking+lunge+tutorial"),
    ("Reverse Lunge", "legs", "none", "beginner",
     "Backward-step lunge that reduces knee stress.",
     "https://www.youtube.com/results?search_query=reverse+lunge+tutorial"),
    ("Lateral Lunge", "legs", "none", "beginner",
     "Side-stepping lunge for inner thigh and glute activation.",
     "https://www.youtube.com/results?search_query=lateral+lunge+tutorial"),
    ("Step-Up", "legs", "dumbbell", "beginner",
     "Elevated platform step for unilateral quad and glute training.",
     "https://www.youtube.com/results?search_query=step+up+exercise+tutorial"),
    ("Barbell Back Squat", "legs", "barbell", "intermediate",
     "Loaded barbell squat for maximum lower-body mass.",
     "https://www.youtube.com/results?search_query=barbell+back+squat+form+tutorial"),
    ("Barbell Front Squat", "legs", "barbell", "intermediate",
     "Front-loaded squat that emphasises the quads.",
     "https://www.youtube.com/results?search_query=barbell+front+squat+tutorial"),
    ("Leg Press", "legs", "machine", "beginner",
     "Machine press for safe, high-volume quad training.",
     "https://www.youtube.com/results?search_query=leg+press+machine+tutorial"),
    ("Leg Extension", "legs", "machine", "beginner",
     "Isolation machine for direct quadriceps training.",
     "https://www.youtube.com/results?search_query=leg+extension+machine+tutorial"),
    ("Leg Curl", "legs", "machine", "beginner",
     "Lying hamstring curl for isolated posterior-chain work.",
     "https://www.youtube.com/results?search_query=leg+curl+machine+tutorial"),
    ("Glute Bridge", "legs", "none", "beginner",
     "Floor hip extension for glute activation and development.",
     "https://www.youtube.com/results?search_query=glute+bridge+tutorial"),
    ("Hip Thrust", "legs", "barbell", "intermediate",
     "Barbell glute bridge for maximum glute strength.",
     "https://www.youtube.com/results?search_query=barbell+hip+thrust+tutorial"),
    ("Calf Raise", "legs", "none", "beginner",
     "Standing or seated raise for gastrocnemius development.",
     "https://www.youtube.com/results?search_query=calf+raise+tutorial"),
    ("Wall Sit", "legs", "none", "beginner",
     "Isometric quad hold for endurance and leg strength.",
     "https://www.youtube.com/results?search_query=wall+sit+tutorial"),
    ("Nordic Hamstring Curl", "legs", "none", "expert",
     "Eccentric hamstring lowering for injury prevention.",
     "https://www.youtube.com/results?search_query=nordic+hamstring+curl+tutorial"),
    ("Box Jump", "legs", "none", "intermediate",
     "Explosive jump onto a platform for power and conditioning.",
     "https://www.youtube.com/results?search_query=box+jump+tutorial"),

    # ── SHOULDERS (20) ─────────────────────────────────────────────────────────
    ("Overhead Press", "shoulders", "barbell", "intermediate",
     "Standing barbell press for overall shoulder mass.",
     "https://www.youtube.com/results?search_query=overhead+press+form+tutorial"),
    ("Seated Dumbbell Press", "shoulders", "dumbbell", "beginner",
     "Seated pressing movement for shoulder stability.",
     "https://www.youtube.com/results?search_query=seated+dumbbell+shoulder+press+tutorial"),
    ("Arnold Press", "shoulders", "dumbbell", "intermediate",
     "Rotating press targeting all three deltoid heads.",
     "https://www.youtube.com/results?search_query=arnold+press+tutorial"),
    ("Lateral Raise", "shoulders", "dumbbell", "beginner",
     "Side dumbbell raise isolating the medial deltoid.",
     "https://www.youtube.com/results?search_query=lateral+raise+tutorial"),
    ("Cable Lateral Raise", "shoulders", "cables", "beginner",
     "Cable lateral raise for constant tension on the medial delt.",
     "https://www.youtube.com/results?search_query=cable+lateral+raise+tutorial"),
    ("Front Raise", "shoulders", "dumbbell", "beginner",
     "Forward dumbbell raise targeting the anterior deltoid.",
     "https://www.youtube.com/results?search_query=front+raise+shoulder+tutorial"),
    ("Rear Delt Fly", "shoulders", "dumbbell", "beginner",
     "Bent-over fly that activates the posterior deltoid.",
     "https://www.youtube.com/results?search_query=rear+delt+fly+tutorial"),
    ("Cable Face Pull", "shoulders", "cables", "beginner",
     "Rope cable pull for rear deltoid and rotator cuff health.",
     "https://www.youtube.com/results?search_query=cable+face+pull+tutorial"),
    ("Upright Row", "shoulders", "barbell", "intermediate",
     "Barbell pull for upper traps and medial deltoid.",
     "https://www.youtube.com/results?search_query=upright+row+tutorial"),
    ("Shrug", "shoulders", "barbell", "beginner",
     "Shoulder elevation for upper trapezius development.",
     "https://www.youtube.com/results?search_query=barbell+shrug+tutorial"),
    ("Push Press", "shoulders", "barbell", "intermediate",
     "Leg-assisted overhead press for power development.",
     "https://www.youtube.com/results?search_query=push+press+tutorial"),
    ("Bradford Press", "shoulders", "barbell", "intermediate",
     "Alternating front and back press targeting all delt heads.",
     "https://www.youtube.com/results?search_query=bradford+press+tutorial"),
    ("Machine Shoulder Press", "shoulders", "machine", "beginner",
     "Guided shoulder press for safe and isolated delt training.",
     "https://www.youtube.com/results?search_query=machine+shoulder+press+tutorial"),
    ("Machine Lateral Raise", "shoulders", "machine", "beginner",
     "Controlled machine raise for the medial deltoid.",
     "https://www.youtube.com/results?search_query=machine+lateral+raise+tutorial"),
    ("Cable Front Raise", "shoulders", "cables", "beginner",
     "Forward cable raise for anterior deltoid.",
     "https://www.youtube.com/results?search_query=cable+front+raise+tutorial"),
    ("Prone Y-T-W", "shoulders", "none", "beginner",
     "Floor-based movement for rear delt and rotator cuff.",
     "https://www.youtube.com/results?search_query=prone+ytw+exercise+tutorial"),
    ("Band Pull-Apart", "shoulders", "none", "beginner",
     "Resistance band row for rear deltoid and shoulder health.",
     "https://www.youtube.com/results?search_query=band+pull+apart+exercise+tutorial"),
    ("Dumbbell Shrug", "shoulders", "dumbbell", "beginner",
     "Shoulder elevation with dumbbells for upper trap training.",
     "https://www.youtube.com/results?search_query=dumbbell+shrug+tutorial"),
    ("Plate Front Raise", "shoulders", "none", "beginner",
     "Front raise with a weight plate for anterior delt strength.",
     "https://www.youtube.com/results?search_query=plate+front+raise+tutorial"),
    ("Single-Arm Cable Press", "shoulders", "cables", "intermediate",
     "Unilateral cable press for shoulder stability and strength.",
     "https://www.youtube.com/results?search_query=single+arm+cable+shoulder+press+tutorial"),

    # ── ARMS (20) ──────────────────────────────────────────────────────────────
    ("Barbell Curl", "arms", "barbell", "beginner",
     "Standard barbell curl for overall biceps mass.",
     "https://www.youtube.com/results?search_query=barbell+curl+form+tutorial"),
    ("Dumbbell Curl", "arms", "dumbbell", "beginner",
     "Alternating curl for balanced bicep development.",
     "https://www.youtube.com/results?search_query=dumbbell+bicep+curl+tutorial"),
    ("Hammer Curl", "arms", "dumbbell", "beginner",
     "Neutral-grip curl for brachialis and forearm thickness.",
     "https://www.youtube.com/results?search_query=hammer+curl+tutorial"),
    ("Incline Dumbbell Curl", "arms", "dumbbell", "intermediate",
     "Incline-position curl for a deep bicep stretch at the bottom.",
     "https://www.youtube.com/results?search_query=incline+dumbbell+curl+tutorial"),
    ("Concentration Curl", "arms", "dumbbell", "beginner",
     "Seated isolated curl for peak bicep contraction.",
     "https://www.youtube.com/results?search_query=concentration+curl+tutorial"),
    ("Cable Curl", "arms", "cables", "beginner",
     "Cable version of the bicep curl for constant tension.",
     "https://www.youtube.com/results?search_query=cable+bicep+curl+tutorial"),
    ("Preacher Curl", "arms", "barbell", "beginner",
     "Arm-supported curl eliminating cheat reps for strict bicep work.",
     "https://www.youtube.com/results?search_query=preacher+curl+tutorial"),
    ("Reverse Curl", "arms", "barbell", "beginner",
     "Overhand-grip curl for brachialis and forearm development.",
     "https://www.youtube.com/results?search_query=reverse+barbell+curl+tutorial"),
    ("21s Curl", "arms", "barbell", "intermediate",
     "Partial-range curl protocol for an intense bicep pump.",
     "https://www.youtube.com/results?search_query=21s+curl+tutorial"),
    ("Zottman Curl", "arms", "dumbbell", "intermediate",
     "Rotating curl that targets both the biceps and forearms.",
     "https://www.youtube.com/results?search_query=zottman+curl+tutorial"),
    ("Tricep Dip", "arms", "none", "intermediate",
     "Bodyweight dip with upright torso isolating the triceps.",
     "https://www.youtube.com/results?search_query=tricep+dip+tutorial"),
    ("Close-Grip Bench Press", "arms", "barbell", "intermediate",
     "Narrow bench press that emphasises the triceps.",
     "https://www.youtube.com/results?search_query=close+grip+bench+press+tutorial"),
    ("Skull Crusher", "arms", "barbell", "intermediate",
     "Lying barbell extension for tricep mass.",
     "https://www.youtube.com/results?search_query=skull+crusher+tricep+tutorial"),
    ("Overhead Tricep Extension", "arms", "dumbbell", "beginner",
     "Dumbbell extension overhead targeting the tricep long head.",
     "https://www.youtube.com/results?search_query=overhead+tricep+extension+tutorial"),
    ("Tricep Pushdown", "arms", "cables", "beginner",
     "Cable pushdown for direct tricep isolation.",
     "https://www.youtube.com/results?search_query=tricep+pushdown+tutorial"),
    ("Rope Pushdown", "arms", "cables", "beginner",
     "Rope attachment pushdown for tricep separation.",
     "https://www.youtube.com/results?search_query=rope+tricep+pushdown+tutorial"),
    ("Tricep Kickback", "arms", "dumbbell", "beginner",
     "Dumbbell extension behind the body for tricep isolation.",
     "https://www.youtube.com/results?search_query=tricep+kickback+tutorial"),
    ("Overhead Cable Extension", "arms", "cables", "beginner",
     "Single-arm cable extension for the tricep long head.",
     "https://www.youtube.com/results?search_query=overhead+cable+tricep+extension+tutorial"),
    ("Wrist Curl", "arms", "dumbbell", "beginner",
     "Forearm curl for wrist flexor development.",
     "https://www.youtube.com/results?search_query=wrist+curl+forearm+tutorial"),
    ("Reverse Wrist Curl", "arms", "dumbbell", "beginner",
     "Forearm reverse curl for wrist extensor strength.",
     "https://www.youtube.com/results?search_query=reverse+wrist+curl+forearm+tutorial"),

    # ── CORE (20) ──────────────────────────────────────────────────────────────
    ("Plank", "core", "none", "beginner",
     "Isometric full-body stabilisation targeting the deep core.",
     "https://www.youtube.com/results?search_query=plank+proper+form+tutorial"),
    ("Side Plank", "core", "none", "beginner",
     "Lateral hold for oblique and hip stability.",
     "https://www.youtube.com/results?search_query=side+plank+tutorial"),
    ("Dead Bug", "core", "none", "beginner",
     "Contralateral arm-leg extension for deep core activation.",
     "https://www.youtube.com/results?search_query=dead+bug+exercise+tutorial"),
    ("Bird Dog", "core", "none", "beginner",
     "Opposite arm-leg extension for balance and spinal stability.",
     "https://www.youtube.com/results?search_query=bird+dog+exercise+tutorial"),
    ("Hollow Body Hold", "core", "none", "intermediate",
     "Gymnastics core compression for full trunk strength.",
     "https://www.youtube.com/results?search_query=hollow+body+hold+tutorial"),
    ("Crunch", "core", "none", "beginner",
     "Classic spinal flexion for upper abdominal training.",
     "https://www.youtube.com/results?search_query=crunch+ab+exercise+tutorial"),
    ("Reverse Crunch", "core", "none", "beginner",
     "Hip-lift crunch targeting the lower abdominals.",
     "https://www.youtube.com/results?search_query=reverse+crunch+tutorial"),
    ("Bicycle Crunch", "core", "none", "beginner",
     "Alternating twist crunch for the obliques and abs.",
     "https://www.youtube.com/results?search_query=bicycle+crunch+tutorial"),
    ("V-Up", "core", "none", "intermediate",
     "Full-range crunch bringing hands and feet together.",
     "https://www.youtube.com/results?search_query=v+up+exercise+tutorial"),
    ("Leg Raise", "core", "none", "intermediate",
     "Lying leg raise for lower abdominal strength.",
     "https://www.youtube.com/results?search_query=lying+leg+raise+tutorial"),
    ("Hanging Knee Raise", "core", "none", "intermediate",
     "Hanging hip flexion for lower abs and hip flexors.",
     "https://www.youtube.com/results?search_query=hanging+knee+raise+tutorial"),
    ("Ab Wheel Rollout", "core", "none", "intermediate",
     "Wheel rollout for total core anti-extension strength.",
     "https://www.youtube.com/results?search_query=ab+wheel+rollout+tutorial"),
    ("Cable Crunch", "core", "cables", "beginner",
     "Weighted kneeling crunch using a rope for loaded ab work.",
     "https://www.youtube.com/results?search_query=cable+crunch+tutorial"),
    ("Russian Twist", "core", "none", "beginner",
     "Rotational core movement for oblique strength.",
     "https://www.youtube.com/results?search_query=russian+twist+tutorial"),
    ("Mountain Climber", "core", "none", "beginner",
     "Dynamic plank with alternating knee drives for core and cardio.",
     "https://www.youtube.com/results?search_query=mountain+climbers+exercise+tutorial"),
    ("Flutter Kick", "core", "none", "beginner",
     "Rapid alternating leg flutter targeting the lower abs.",
     "https://www.youtube.com/results?search_query=flutter+kicks+exercise+tutorial"),
    ("Pallof Press", "core", "cables", "intermediate",
     "Anti-rotation cable press for lateral core stability.",
     "https://www.youtube.com/results?search_query=pallof+press+tutorial"),
    ("Cable Woodchop", "core", "cables", "intermediate",
     "Rotational cable chop for functional core power.",
     "https://www.youtube.com/results?search_query=cable+woodchop+tutorial"),
    ("Dragon Flag", "core", "none", "expert",
     "Advanced full-body spinal flexion for extreme core strength.",
     "https://www.youtube.com/results?search_query=dragon+flag+exercise+tutorial"),
    ("Windmill", "core", "kettlebell", "intermediate",
     "Hip-hinge rotation with overhead weight for oblique and glute work.",
     "https://www.youtube.com/results?search_query=kettlebell+windmill+tutorial"),

    # ── CARDIO (20) ────────────────────────────────────────────────────────────
    ("Jumping Jack", "cardio", "none", "beginner",
     "Full-body plyometric movement for cardiovascular warm-up.",
     "https://www.youtube.com/results?search_query=jumping+jacks+tutorial"),
    ("Burpee", "cardio", "none", "intermediate",
     "High-intensity full-body exercise combining squat, plank, and jump.",
     "https://www.youtube.com/results?search_query=burpee+proper+form+tutorial"),
    ("High Knees", "cardio", "none", "beginner",
     "Running in place with exaggerated knee drive for cardio intensity.",
     "https://www.youtube.com/results?search_query=high+knees+exercise+tutorial"),
    ("Jump Rope", "cardio", "none", "beginner",
     "Continuous rope skipping for coordination and cardiovascular fitness.",
     "https://www.youtube.com/results?search_query=jump+rope+tutorial+beginners"),
    ("Sprint", "cardio", "none", "intermediate",
     "Maximum-effort short-distance run for speed and anaerobic power.",
     "https://www.youtube.com/results?search_query=sprint+training+tutorial"),
    ("Jump Squat", "cardio", "none", "intermediate",
     "Explosive squat with a vertical jump for power and conditioning.",
     "https://www.youtube.com/results?search_query=jump+squat+tutorial"),
    ("Lateral Shuffle", "cardio", "none", "beginner",
     "Side-to-side shuffling for agility and hip activation.",
     "https://www.youtube.com/results?search_query=lateral+shuffle+drill+tutorial"),
    ("Stair Climb", "cardio", "none", "beginner",
     "Climbing stairs for lower-body and cardiovascular conditioning.",
     "https://www.youtube.com/results?search_query=stair+climbing+workout+tutorial"),
    ("Rowing Machine", "cardio", "machine", "beginner",
     "Full-body ergometer row for cardiovascular endurance.",
     "https://www.youtube.com/results?search_query=rowing+machine+form+tutorial"),
    ("Cycling", "cardio", "machine", "beginner",
     "Stationary bike riding for low-impact cardiovascular fitness.",
     "https://www.youtube.com/results?search_query=stationary+bike+workout+tutorial"),
    ("Elliptical", "cardio", "machine", "beginner",
     "Low-impact gliding movement for full-body cardiovascular work.",
     "https://www.youtube.com/results?search_query=elliptical+machine+tutorial"),
    ("Bear Crawl", "cardio", "none", "beginner",
     "Quadruped forward movement engaging the full body.",
     "https://www.youtube.com/results?search_query=bear+crawl+exercise+tutorial"),
    ("Sled Push", "cardio", "none", "intermediate",
     "Loaded sled drive for conditioning and lower-body power.",
     "https://www.youtube.com/results?search_query=sled+push+workout+tutorial"),
    ("Battle Ropes", "cardio", "none", "beginner",
     "Wave or slam rope movement for high-intensity conditioning.",
     "https://www.youtube.com/results?search_query=battle+ropes+exercise+tutorial"),
    ("Kettlebell Swing", "cardio", "kettlebell", "intermediate",
     "Hip-hinge swing for cardiovascular and posterior-chain training.",
     "https://www.youtube.com/results?search_query=kettlebell+swing+tutorial"),
    ("Treadmill Run", "cardio", "machine", "beginner",
     "Controlled-pace run for aerobic endurance.",
     "https://www.youtube.com/results?search_query=treadmill+running+form+tutorial"),
    ("Assault Bike", "cardio", "machine", "intermediate",
     "Full-body push-pull bike for maximum conditioning output.",
     "https://www.youtube.com/results?search_query=assault+bike+workout+tutorial"),
    ("Ski Erg", "cardio", "machine", "intermediate",
     "Skiing simulation for upper-body and cardiovascular training.",
     "https://www.youtube.com/results?search_query=ski+erg+tutorial"),
    ("Medicine Ball Slam", "cardio", "none", "intermediate",
     "Overhead slam for explosive power and conditioning.",
     "https://www.youtube.com/results?search_query=medicine+ball+slam+tutorial"),
    ("Burpee Box Jump", "cardio", "none", "expert",
     "Burpee combined with a box jump for maximum intensity.",
     "https://www.youtube.com/results?search_query=burpee+box+jump+tutorial"),
]


class Command(BaseCommand):
    help = 'Seed the database with 20 exercises per muscle group'

    def handle(self, *args, **options):
        created = 0
        skipped = 0

        for (name, muscle, equipment, difficulty, description, video_url) in EXERCISES:
            obj, was_created = Exercise.objects.get_or_create(
                name=name,
                defaults=dict(
                    muscle_group=muscle,
                    equipment=equipment,
                    difficulty=difficulty,
                    description=description,
                    video_url=video_url,
                ),
            )
            if was_created:
                created += 1
            else:
                skipped += 1

        self.stdout.write(
            self.style.SUCCESS(
                f'Done — {created} exercises created, {skipped} already existed.'
            )
        )
